import { db } from "./db";
import { countries, regions, cities } from "@shared/schema";

// Comprehensive world countries data with ISO codes, flags, and continents
const worldCountries = [
  // Africa
  { name: "Algeria", code: "DZ", slug: "algeria", flag: "🇩🇿", continent: "Africa" },
  { name: "Angola", code: "AO", slug: "angola", flag: "🇦🇴", continent: "Africa" },
  { name: "Benin", code: "BJ", slug: "benin", flag: "🇧🇯", continent: "Africa" },
  { name: "Botswana", code: "BW", slug: "botswana", flag: "🇧🇼", continent: "Africa" },
  { name: "Burkina Faso", code: "BF", slug: "burkina-faso", flag: "🇧🇫", continent: "Africa" },
  { name: "Burundi", code: "BI", slug: "burundi", flag: "🇧🇮", continent: "Africa" },
  { name: "Cameroon", code: "CM", slug: "cameroon", flag: "🇨🇲", continent: "Africa" },
  { name: "Cape Verde", code: "CV", slug: "cape-verde", flag: "🇨🇻", continent: "Africa" },
  { name: "Central African Republic", code: "CF", slug: "central-african-republic", flag: "🇨🇫", continent: "Africa" },
  { name: "Chad", code: "TD", slug: "chad", flag: "🇹🇩", continent: "Africa" },
  { name: "Comoros", code: "KM", slug: "comoros", flag: "🇰🇲", continent: "Africa" },
  { name: "Congo", code: "CG", slug: "congo", flag: "🇨🇬", continent: "Africa" },
  { name: "Democratic Republic of the Congo", code: "CD", slug: "dr-congo", flag: "🇨🇩", continent: "Africa" },
  { name: "Djibouti", code: "DJ", slug: "djibouti", flag: "🇩🇯", continent: "Africa" },
  { name: "Egypt", code: "EG", slug: "egypt", flag: "🇪🇬", continent: "Africa" },
  { name: "Equatorial Guinea", code: "GQ", slug: "equatorial-guinea", flag: "🇬🇶", continent: "Africa" },
  { name: "Eritrea", code: "ER", slug: "eritrea", flag: "🇪🇷", continent: "Africa" },
  { name: "Ethiopia", code: "ET", slug: "ethiopia", flag: "🇪🇹", continent: "Africa" },
  { name: "Gabon", code: "GA", slug: "gabon", flag: "🇬🇦", continent: "Africa" },
  { name: "Gambia", code: "GM", slug: "gambia", flag: "🇬🇲", continent: "Africa" },
  { name: "Ghana", code: "GH", slug: "ghana", flag: "🇬🇭", continent: "Africa" },
  { name: "Guinea", code: "GN", slug: "guinea", flag: "🇬🇳", continent: "Africa" },
  { name: "Guinea-Bissau", code: "GW", slug: "guinea-bissau", flag: "🇬🇼", continent: "Africa" },
  { name: "Ivory Coast", code: "CI", slug: "ivory-coast", flag: "🇨🇮", continent: "Africa" },
  { name: "Kenya", code: "KE", slug: "kenya", flag: "🇰🇪", continent: "Africa" },
  { name: "Lesotho", code: "LS", slug: "lesotho", flag: "🇱🇸", continent: "Africa" },
  { name: "Liberia", code: "LR", slug: "liberia", flag: "🇱🇷", continent: "Africa" },
  { name: "Libya", code: "LY", slug: "libya", flag: "🇱🇾", continent: "Africa" },
  { name: "Madagascar", code: "MG", slug: "madagascar", flag: "🇲🇬", continent: "Africa" },
  { name: "Malawi", code: "MW", slug: "malawi", flag: "🇲🇼", continent: "Africa" },
  { name: "Mali", code: "ML", slug: "mali", flag: "🇲🇱", continent: "Africa" },
  { name: "Mauritania", code: "MR", slug: "mauritania", flag: "🇲🇷", continent: "Africa" },
  { name: "Mauritius", code: "MU", slug: "mauritius", flag: "🇲🇺", continent: "Africa" },
  { name: "Morocco", code: "MA", slug: "morocco", flag: "🇲🇦", continent: "Africa" },
  { name: "Mozambique", code: "MZ", slug: "mozambique", flag: "🇲🇿", continent: "Africa" },
  { name: "Namibia", code: "NA", slug: "namibia", flag: "🇳🇦", continent: "Africa" },
  { name: "Niger", code: "NE", slug: "niger", flag: "🇳🇪", continent: "Africa" },
  { name: "Nigeria", code: "NG", slug: "nigeria", flag: "🇳🇬", continent: "Africa" },
  { name: "Rwanda", code: "RW", slug: "rwanda", flag: "🇷🇼", continent: "Africa" },
  { name: "Sao Tome and Principe", code: "ST", slug: "sao-tome-principe", flag: "🇸🇹", continent: "Africa" },
  { name: "Senegal", code: "SN", slug: "senegal", flag: "🇸🇳", continent: "Africa" },
  { name: "Seychelles", code: "SC", slug: "seychelles", flag: "🇸🇨", continent: "Africa" },
  { name: "Sierra Leone", code: "SL", slug: "sierra-leone", flag: "🇸🇱", continent: "Africa" },
  { name: "Somalia", code: "SO", slug: "somalia", flag: "🇸🇴", continent: "Africa" },
  { name: "South Africa", code: "ZA", slug: "south-africa", flag: "🇿🇦", continent: "Africa" },
  { name: "South Sudan", code: "SS", slug: "south-sudan", flag: "🇸🇸", continent: "Africa" },
  { name: "Sudan", code: "SD", slug: "sudan", flag: "🇸🇩", continent: "Africa" },
  { name: "Tanzania", code: "TZ", slug: "tanzania", flag: "🇹🇿", continent: "Africa" },
  { name: "Togo", code: "TG", slug: "togo", flag: "🇹🇬", continent: "Africa" },
  { name: "Tunisia", code: "TN", slug: "tunisia", flag: "🇹🇳", continent: "Africa" },
  { name: "Uganda", code: "UG", slug: "uganda", flag: "🇺🇬", continent: "Africa" },
  { name: "Zambia", code: "ZM", slug: "zambia", flag: "🇿🇲", continent: "Africa" },
  { name: "Zimbabwe", code: "ZW", slug: "zimbabwe", flag: "🇿🇼", continent: "Africa" },
  
  // Asia
  { name: "Afghanistan", code: "AF", slug: "afghanistan", flag: "🇦🇫", continent: "Asia" },
  { name: "Armenia", code: "AM", slug: "armenia", flag: "🇦🇲", continent: "Asia" },
  { name: "Azerbaijan", code: "AZ", slug: "azerbaijan", flag: "🇦🇿", continent: "Asia" },
  { name: "Bahrain", code: "BH", slug: "bahrain", flag: "🇧🇭", continent: "Asia" },
  { name: "Bangladesh", code: "BD", slug: "bangladesh", flag: "🇧🇩", continent: "Asia" },
  { name: "Bhutan", code: "BT", slug: "bhutan", flag: "🇧🇹", continent: "Asia" },
  { name: "Brunei", code: "BN", slug: "brunei", flag: "🇧🇳", continent: "Asia" },
  { name: "Cambodia", code: "KH", slug: "cambodia", flag: "🇰🇭", continent: "Asia" },
  { name: "China", code: "CN", slug: "china", flag: "🇨🇳", continent: "Asia" },
  { name: "Georgia", code: "GE", slug: "georgia", flag: "🇬🇪", continent: "Asia" },
  { name: "India", code: "IN", slug: "india", flag: "🇮🇳", continent: "Asia" },
  { name: "Indonesia", code: "ID", slug: "indonesia", flag: "🇮🇩", continent: "Asia" },
  { name: "Iran", code: "IR", slug: "iran", flag: "🇮🇷", continent: "Asia" },
  { name: "Iraq", code: "IQ", slug: "iraq", flag: "🇮🇶", continent: "Asia" },
  { name: "Israel", code: "IL", slug: "israel", flag: "🇮🇱", continent: "Asia" },
  { name: "Japan", code: "JP", slug: "japan", flag: "🇯🇵", continent: "Asia" },
  { name: "Jordan", code: "JO", slug: "jordan", flag: "🇯🇴", continent: "Asia" },
  { name: "Kazakhstan", code: "KZ", slug: "kazakhstan", flag: "🇰🇿", continent: "Asia" },
  { name: "Kuwait", code: "KW", slug: "kuwait", flag: "🇰🇼", continent: "Asia" },
  { name: "Kyrgyzstan", code: "KG", slug: "kyrgyzstan", flag: "🇰🇬", continent: "Asia" },
  { name: "Laos", code: "LA", slug: "laos", flag: "🇱🇦", continent: "Asia" },
  { name: "Lebanon", code: "LB", slug: "lebanon", flag: "🇱🇧", continent: "Asia" },
  { name: "Malaysia", code: "MY", slug: "malaysia", flag: "🇲🇾", continent: "Asia" },
  { name: "Maldives", code: "MV", slug: "maldives", flag: "🇲🇻", continent: "Asia" },
  { name: "Mongolia", code: "MN", slug: "mongolia", flag: "🇲🇳", continent: "Asia" },
  { name: "Myanmar", code: "MM", slug: "myanmar", flag: "🇲🇲", continent: "Asia" },
  { name: "Nepal", code: "NP", slug: "nepal", flag: "🇳🇵", continent: "Asia" },
  { name: "North Korea", code: "KP", slug: "north-korea", flag: "🇰🇵", continent: "Asia" },
  { name: "Oman", code: "OM", slug: "oman", flag: "🇴🇲", continent: "Asia" },
  { name: "Pakistan", code: "PK", slug: "pakistan", flag: "🇵🇰", continent: "Asia" },
  { name: "Palestine", code: "PS", slug: "palestine", flag: "🇵🇸", continent: "Asia" },
  { name: "Philippines", code: "PH", slug: "philippines", flag: "🇵🇭", continent: "Asia" },
  { name: "Qatar", code: "QA", slug: "qatar", flag: "🇶🇦", continent: "Asia" },
  { name: "Saudi Arabia", code: "SA", slug: "saudi-arabia", flag: "🇸🇦", continent: "Asia" },
  { name: "Singapore", code: "SG", slug: "singapore", flag: "🇸🇬", continent: "Asia" },
  { name: "South Korea", code: "KR", slug: "south-korea", flag: "🇰🇷", continent: "Asia" },
  { name: "Sri Lanka", code: "LK", slug: "sri-lanka", flag: "🇱🇰", continent: "Asia" },
  { name: "Syria", code: "SY", slug: "syria", flag: "🇸🇾", continent: "Asia" },
  { name: "Taiwan", code: "TW", slug: "taiwan", flag: "🇹🇼", continent: "Asia" },
  { name: "Tajikistan", code: "TJ", slug: "tajikistan", flag: "🇹🇯", continent: "Asia" },
  { name: "Thailand", code: "TH", slug: "thailand", flag: "🇹🇭", continent: "Asia" },
  { name: "Timor-Leste", code: "TL", slug: "timor-leste", flag: "🇹🇱", continent: "Asia" },
  { name: "Turkey", code: "TR", slug: "turkey", flag: "🇹🇷", continent: "Asia" },
  { name: "Turkmenistan", code: "TM", slug: "turkmenistan", flag: "🇹🇲", continent: "Asia" },
  { name: "United Arab Emirates", code: "AE", slug: "uae", flag: "🇦🇪", continent: "Asia" },
  { name: "Uzbekistan", code: "UZ", slug: "uzbekistan", flag: "🇺🇿", continent: "Asia" },
  { name: "Vietnam", code: "VN", slug: "vietnam", flag: "🇻🇳", continent: "Asia" },
  { name: "Yemen", code: "YE", slug: "yemen", flag: "🇾🇪", continent: "Asia" },
  
  // Europe
  { name: "Albania", code: "AL", slug: "albania", flag: "🇦🇱", continent: "Europe" },
  { name: "Andorra", code: "AD", slug: "andorra", flag: "🇦🇩", continent: "Europe" },
  { name: "Austria", code: "AT", slug: "austria", flag: "🇦🇹", continent: "Europe" },
  { name: "Belarus", code: "BY", slug: "belarus", flag: "🇧🇾", continent: "Europe" },
  { name: "Belgium", code: "BE", slug: "belgium", flag: "🇧🇪", continent: "Europe" },
  { name: "Bosnia and Herzegovina", code: "BA", slug: "bosnia", flag: "🇧🇦", continent: "Europe" },
  { name: "Bulgaria", code: "BG", slug: "bulgaria", flag: "🇧🇬", continent: "Europe" },
  { name: "Croatia", code: "HR", slug: "croatia", flag: "🇭🇷", continent: "Europe" },
  { name: "Cyprus", code: "CY", slug: "cyprus", flag: "🇨🇾", continent: "Europe" },
  { name: "Czech Republic", code: "CZ", slug: "czech-republic", flag: "🇨🇿", continent: "Europe" },
  { name: "Denmark", code: "DK", slug: "denmark", flag: "🇩🇰", continent: "Europe" },
  { name: "Estonia", code: "EE", slug: "estonia", flag: "🇪🇪", continent: "Europe" },
  { name: "Finland", code: "FI", slug: "finland", flag: "🇫🇮", continent: "Europe" },
  { name: "France", code: "FR", slug: "france", flag: "🇫🇷", continent: "Europe" },
  { name: "Germany", code: "DE", slug: "germany", flag: "🇩🇪", continent: "Europe" },
  { name: "Greece", code: "GR", slug: "greece", flag: "🇬🇷", continent: "Europe" },
  { name: "Hungary", code: "HU", slug: "hungary", flag: "🇭🇺", continent: "Europe" },
  { name: "Iceland", code: "IS", slug: "iceland", flag: "🇮🇸", continent: "Europe" },
  { name: "Ireland", code: "IE", slug: "ireland", flag: "🇮🇪", continent: "Europe" },
  { name: "Italy", code: "IT", slug: "italy", flag: "🇮🇹", continent: "Europe" },
  { name: "Kosovo", code: "XK", slug: "kosovo", flag: "🇽🇰", continent: "Europe" },
  { name: "Latvia", code: "LV", slug: "latvia", flag: "🇱🇻", continent: "Europe" },
  { name: "Liechtenstein", code: "LI", slug: "liechtenstein", flag: "🇱🇮", continent: "Europe" },
  { name: "Lithuania", code: "LT", slug: "lithuania", flag: "🇱🇹", continent: "Europe" },
  { name: "Luxembourg", code: "LU", slug: "luxembourg", flag: "🇱🇺", continent: "Europe" },
  { name: "Malta", code: "MT", slug: "malta", flag: "🇲🇹", continent: "Europe" },
  { name: "Moldova", code: "MD", slug: "moldova", flag: "🇲🇩", continent: "Europe" },
  { name: "Monaco", code: "MC", slug: "monaco", flag: "🇲🇨", continent: "Europe" },
  { name: "Montenegro", code: "ME", slug: "montenegro", flag: "🇲🇪", continent: "Europe" },
  { name: "Netherlands", code: "NL", slug: "netherlands", flag: "🇳🇱", continent: "Europe" },
  { name: "North Macedonia", code: "MK", slug: "north-macedonia", flag: "🇲🇰", continent: "Europe" },
  { name: "Norway", code: "NO", slug: "norway", flag: "🇳🇴", continent: "Europe" },
  { name: "Poland", code: "PL", slug: "poland", flag: "🇵🇱", continent: "Europe" },
  { name: "Portugal", code: "PT", slug: "portugal", flag: "🇵🇹", continent: "Europe" },
  { name: "Romania", code: "RO", slug: "romania", flag: "🇷🇴", continent: "Europe" },
  { name: "Russia", code: "RU", slug: "russia", flag: "🇷🇺", continent: "Europe" },
  { name: "San Marino", code: "SM", slug: "san-marino", flag: "🇸🇲", continent: "Europe" },
  { name: "Serbia", code: "RS", slug: "serbia", flag: "🇷🇸", continent: "Europe" },
  { name: "Slovakia", code: "SK", slug: "slovakia", flag: "🇸🇰", continent: "Europe" },
  { name: "Slovenia", code: "SI", slug: "slovenia", flag: "🇸🇮", continent: "Europe" },
  { name: "Spain", code: "ES", slug: "spain", flag: "🇪🇸", continent: "Europe" },
  { name: "Sweden", code: "SE", slug: "sweden", flag: "🇸🇪", continent: "Europe" },
  { name: "Switzerland", code: "CH", slug: "switzerland", flag: "🇨🇭", continent: "Europe" },
  { name: "Ukraine", code: "UA", slug: "ukraine", flag: "🇺🇦", continent: "Europe" },
  { name: "United Kingdom", code: "GB", slug: "uk", flag: "🇬🇧", continent: "Europe" },
  { name: "Vatican City", code: "VA", slug: "vatican", flag: "🇻🇦", continent: "Europe" },
  
  // North America
  { name: "Antigua and Barbuda", code: "AG", slug: "antigua-barbuda", flag: "🇦🇬", continent: "North America" },
  { name: "Bahamas", code: "BS", slug: "bahamas", flag: "🇧🇸", continent: "North America" },
  { name: "Barbados", code: "BB", slug: "barbados", flag: "🇧🇧", continent: "North America" },
  { name: "Belize", code: "BZ", slug: "belize", flag: "🇧🇿", continent: "North America" },
  { name: "Canada", code: "CA", slug: "canada", flag: "🇨🇦", continent: "North America" },
  { name: "Costa Rica", code: "CR", slug: "costa-rica", flag: "🇨🇷", continent: "North America" },
  { name: "Cuba", code: "CU", slug: "cuba", flag: "🇨🇺", continent: "North America" },
  { name: "Dominica", code: "DM", slug: "dominica", flag: "🇩🇲", continent: "North America" },
  { name: "Dominican Republic", code: "DO", slug: "dominican-republic", flag: "🇩🇴", continent: "North America" },
  { name: "El Salvador", code: "SV", slug: "el-salvador", flag: "🇸🇻", continent: "North America" },
  { name: "Grenada", code: "GD", slug: "grenada", flag: "🇬🇩", continent: "North America" },
  { name: "Guatemala", code: "GT", slug: "guatemala", flag: "🇬🇹", continent: "North America" },
  { name: "Haiti", code: "HT", slug: "haiti", flag: "🇭🇹", continent: "North America" },
  { name: "Honduras", code: "HN", slug: "honduras", flag: "🇭🇳", continent: "North America" },
  { name: "Jamaica", code: "JM", slug: "jamaica", flag: "🇯🇲", continent: "North America" },
  { name: "Mexico", code: "MX", slug: "mexico", flag: "🇲🇽", continent: "North America" },
  { name: "Nicaragua", code: "NI", slug: "nicaragua", flag: "🇳🇮", continent: "North America" },
  { name: "Panama", code: "PA", slug: "panama", flag: "🇵🇦", continent: "North America" },
  { name: "Saint Kitts and Nevis", code: "KN", slug: "saint-kitts-nevis", flag: "🇰🇳", continent: "North America" },
  { name: "Saint Lucia", code: "LC", slug: "saint-lucia", flag: "🇱🇨", continent: "North America" },
  { name: "Saint Vincent and the Grenadines", code: "VC", slug: "saint-vincent-grenadines", flag: "🇻🇨", continent: "North America" },
  { name: "Trinidad and Tobago", code: "TT", slug: "trinidad-tobago", flag: "🇹🇹", continent: "North America" },
  { name: "United States", code: "US", slug: "usa", flag: "🇺🇸", continent: "North America" },
  
  // South America
  { name: "Argentina", code: "AR", slug: "argentina", flag: "🇦🇷", continent: "South America" },
  { name: "Bolivia", code: "BO", slug: "bolivia", flag: "🇧🇴", continent: "South America" },
  { name: "Brazil", code: "BR", slug: "brazil", flag: "🇧🇷", continent: "South America" },
  { name: "Chile", code: "CL", slug: "chile", flag: "🇨🇱", continent: "South America" },
  { name: "Colombia", code: "CO", slug: "colombia", flag: "🇨🇴", continent: "South America" },
  { name: "Ecuador", code: "EC", slug: "ecuador", flag: "🇪🇨", continent: "South America" },
  { name: "Guyana", code: "GY", slug: "guyana", flag: "🇬🇾", continent: "South America" },
  { name: "Paraguay", code: "PY", slug: "paraguay", flag: "🇵🇾", continent: "South America" },
  { name: "Peru", code: "PE", slug: "peru", flag: "🇵🇪", continent: "South America" },
  { name: "Suriname", code: "SR", slug: "suriname", flag: "🇸🇷", continent: "South America" },
  { name: "Uruguay", code: "UY", slug: "uruguay", flag: "🇺🇾", continent: "South America" },
  { name: "Venezuela", code: "VE", slug: "venezuela", flag: "🇻🇪", continent: "South America" },
  
  // Oceania
  { name: "Australia", code: "AU", slug: "australia", flag: "🇦🇺", continent: "Oceania" },
  { name: "Fiji", code: "FJ", slug: "fiji", flag: "🇫🇯", continent: "Oceania" },
  { name: "Kiribati", code: "KI", slug: "kiribati", flag: "🇰🇮", continent: "Oceania" },
  { name: "Marshall Islands", code: "MH", slug: "marshall-islands", flag: "🇲🇭", continent: "Oceania" },
  { name: "Micronesia", code: "FM", slug: "micronesia", flag: "🇫🇲", continent: "Oceania" },
  { name: "Nauru", code: "NR", slug: "nauru", flag: "🇳🇷", continent: "Oceania" },
  { name: "New Zealand", code: "NZ", slug: "new-zealand", flag: "🇳🇿", continent: "Oceania" },
  { name: "Palau", code: "PW", slug: "palau", flag: "🇵🇼", continent: "Oceania" },
  { name: "Papua New Guinea", code: "PG", slug: "papua-new-guinea", flag: "🇵🇬", continent: "Oceania" },
  { name: "Samoa", code: "WS", slug: "samoa", flag: "🇼🇸", continent: "Oceania" },
  { name: "Solomon Islands", code: "SB", slug: "solomon-islands", flag: "🇸🇧", continent: "Oceania" },
  { name: "Tonga", code: "TO", slug: "tonga", flag: "🇹🇴", continent: "Oceania" },
  { name: "Tuvalu", code: "TV", slug: "tuvalu", flag: "🇹🇻", continent: "Oceania" },
  { name: "Vanuatu", code: "VU", slug: "vanuatu", flag: "🇻🇺", continent: "Oceania" },
];

// Capital cities for each country
const capitalCities: Record<string, { name: string; latitude?: string; longitude?: string; population?: number }> = {
  "DZ": { name: "Algiers", latitude: "36.7372", longitude: "3.0865", population: 2988000 },
  "AO": { name: "Luanda", latitude: "8.8383", longitude: "13.2344", population: 8330000 },
  "BJ": { name: "Porto-Novo", latitude: "6.4969", longitude: "2.6289", population: 264320 },
  "BW": { name: "Gaborone", latitude: "-24.6282", longitude: "25.9231", population: 231626 },
  "BF": { name: "Ouagadougou", latitude: "12.3686", longitude: "-1.5275", population: 2200000 },
  "BI": { name: "Bujumbura", latitude: "-3.3614", longitude: "29.3599", population: 800000 },
  "CM": { name: "Yaoundé", latitude: "3.8480", longitude: "11.5021", population: 3412000 },
  "CV": { name: "Praia", latitude: "14.9177", longitude: "-23.5092", population: 159000 },
  "CF": { name: "Bangui", latitude: "4.3947", longitude: "18.5582", population: 734350 },
  "TD": { name: "N'Djamena", latitude: "12.1348", longitude: "15.0557", population: 1092000 },
  "KM": { name: "Moroni", latitude: "-11.7172", longitude: "43.2473", population: 60200 },
  "CG": { name: "Brazzaville", latitude: "-4.2634", longitude: "15.2429", population: 2230000 },
  "CD": { name: "Kinshasa", latitude: "-4.3276", longitude: "15.3136", population: 14342000 },
  "DJ": { name: "Djibouti", latitude: "11.5721", longitude: "43.1456", population: 600000 },
  "EG": { name: "Cairo", latitude: "30.0444", longitude: "31.2357", population: 20484965 },
  "GQ": { name: "Malabo", latitude: "3.7523", longitude: "8.7741", population: 145000 },
  "ER": { name: "Asmara", latitude: "15.3229", longitude: "38.9251", population: 963000 },
  "ET": { name: "Addis Ababa", latitude: "9.0054", longitude: "38.7636", population: 3384569 },
  "GA": { name: "Libreville", latitude: "0.3924", longitude: "9.4535", population: 703904 },
  "GM": { name: "Banjul", latitude: "13.4549", longitude: "-16.5790", population: 31301 },
  "GH": { name: "Accra", latitude: "5.6037", longitude: "-0.1870", population: 2291352 },
  "GN": { name: "Conakry", latitude: "9.5092", longitude: "-13.7122", population: 1667864 },
  "GW": { name: "Bissau", latitude: "11.8636", longitude: "-15.5984", population: 395954 },
  "CI": { name: "Yamoussoukro", latitude: "6.8276", longitude: "-5.2893", population: 355573 },
  "KE": { name: "Nairobi", latitude: "-1.2864", longitude: "36.8172", population: 4397073 },
  "LS": { name: "Maseru", latitude: "-29.3167", longitude: "27.4833", population: 330760 },
  "LR": { name: "Monrovia", latitude: "6.3005", longitude: "-10.7969", population: 1010970 },
  "LY": { name: "Tripoli", latitude: "32.8872", longitude: "13.1913", population: 1150989 },
  "MG": { name: "Antananarivo", latitude: "-18.8792", longitude: "47.5079", population: 1275207 },
  "MW": { name: "Lilongwe", latitude: "-13.9626", longitude: "33.7741", population: 905964 },
  "ML": { name: "Bamako", latitude: "12.6392", longitude: "-8.0029", population: 2447000 },
  "MR": { name: "Nouakchott", latitude: "18.0735", longitude: "-15.9582", population: 1205000 },
  "MU": { name: "Port Louis", latitude: "-20.1609", longitude: "57.5012", population: 147066 },
  "MA": { name: "Rabat", latitude: "33.9716", longitude: "-6.8498", population: 577827 },
  "MZ": { name: "Maputo", latitude: "-25.9655", longitude: "32.5832", population: 1101170 },
  "NA": { name: "Windhoek", latitude: "-22.5597", longitude: "17.0832", population: 325858 },
  "NE": { name: "Niamey", latitude: "13.5127", longitude: "2.1127", population: 1026848 },
  "NG": { name: "Abuja", latitude: "9.0579", longitude: "7.4951", population: 1770000 },
  "RW": { name: "Kigali", latitude: "-1.9403", longitude: "29.8739", population: 1132686 },
  "ST": { name: "São Tomé", latitude: "0.3365", longitude: "6.7273", population: 71868 },
  "SN": { name: "Dakar", latitude: "14.7167", longitude: "-17.4677", population: 1146053 },
  "SC": { name: "Victoria", latitude: "-4.6236", longitude: "55.4544", population: 26450 },
  "SL": { name: "Freetown", latitude: "8.4657", longitude: "-13.2317", population: 1055964 },
  "SO": { name: "Mogadishu", latitude: "2.0469", longitude: "45.3182", population: 2120000 },
  "ZA": { name: "Pretoria", latitude: "-25.7461", longitude: "28.1881", population: 741651 },
  "SS": { name: "Juba", latitude: "4.8594", longitude: "31.5713", population: 372410 },
  "SD": { name: "Khartoum", latitude: "15.5007", longitude: "32.5599", population: 5274321 },
  "TZ": { name: "Dodoma", latitude: "-6.1630", longitude: "35.7516", population: 410956 },
  "TG": { name: "Lomé", latitude: "6.1256", longitude: "1.2215", population: 837437 },
  "TN": { name: "Tunis", latitude: "36.8065", longitude: "10.1815", population: 1056247 },
  "UG": { name: "Kampala", latitude: "0.3476", longitude: "32.5825", population: 1680000 },
  "ZM": { name: "Lusaka", latitude: "-15.3875", longitude: "28.3228", population: 2524000 },
  "ZW": { name: "Harare", latitude: "-17.8292", longitude: "31.0522", population: 1606000 },
  
  // Asia
  "AF": { name: "Kabul", latitude: "34.5553", longitude: "69.2075", population: 4273156 },
  "AM": { name: "Yerevan", latitude: "40.1872", longitude: "44.5152", population: 1082000 },
  "AZ": { name: "Baku", latitude: "40.4093", longitude: "49.8671", population: 2236000 },
  "BH": { name: "Manama", latitude: "26.2285", longitude: "50.5860", population: 147074 },
  "BD": { name: "Dhaka", latitude: "23.8103", longitude: "90.4125", population: 21005860 },
  "BT": { name: "Thimphu", latitude: "27.4728", longitude: "89.6390", population: 104000 },
  "BN": { name: "Bandar Seri Begawan", latitude: "4.8895", longitude: "114.9420", population: 100700 },
  "KH": { name: "Phnom Penh", latitude: "11.5564", longitude: "104.9282", population: 2129371 },
  "CN": { name: "Beijing", latitude: "39.9042", longitude: "116.4074", population: 21540000 },
  "GE": { name: "Tbilisi", latitude: "41.7151", longitude: "44.8271", population: 1118000 },
  "IN": { name: "New Delhi", latitude: "28.6139", longitude: "77.2090", population: 32941000 },
  "ID": { name: "Jakarta", latitude: "-6.2088", longitude: "106.8456", population: 10770000 },
  "IR": { name: "Tehran", latitude: "35.6892", longitude: "51.3890", population: 8896000 },
  "IQ": { name: "Baghdad", latitude: "33.3128", longitude: "44.3615", population: 7144260 },
  "IL": { name: "Jerusalem", latitude: "31.7683", longitude: "35.2137", population: 936425 },
  "JP": { name: "Tokyo", latitude: "35.6762", longitude: "139.6503", population: 13960000 },
  "JO": { name: "Amman", latitude: "31.9454", longitude: "35.9284", population: 2130000 },
  "KZ": { name: "Astana", latitude: "51.1694", longitude: "71.4491", population: 1078362 },
  "KW": { name: "Kuwait City", latitude: "29.3759", longitude: "47.9774", population: 3050000 },
  "KG": { name: "Bishkek", latitude: "42.8746", longitude: "74.5698", population: 1074000 },
  "LA": { name: "Vientiane", latitude: "17.9757", longitude: "102.6331", population: 997240 },
  "LB": { name: "Beirut", latitude: "33.8886", longitude: "35.4955", population: 361366 },
  "MY": { name: "Kuala Lumpur", latitude: "3.1390", longitude: "101.6869", population: 1768000 },
  "MV": { name: "Malé", latitude: "4.1755", longitude: "73.5093", population: 133412 },
  "MN": { name: "Ulaanbaatar", latitude: "47.8864", longitude: "106.9057", population: 1520000 },
  "MM": { name: "Naypyidaw", latitude: "19.7633", longitude: "96.0785", population: 1250000 },
  "NP": { name: "Kathmandu", latitude: "27.7172", longitude: "85.3240", population: 1003285 },
  "KP": { name: "Pyongyang", latitude: "39.0392", longitude: "125.7625", population: 3038000 },
  "OM": { name: "Muscat", latitude: "23.5880", longitude: "58.3829", population: 1560330 },
  "PK": { name: "Islamabad", latitude: "33.6844", longitude: "73.0479", population: 1129198 },
  "PS": { name: "Jerusalem", latitude: "31.7683", longitude: "35.2137", population: 936425 },
  "PH": { name: "Manila", latitude: "14.5995", longitude: "120.9842", population: 1846513 },
  "QA": { name: "Doha", latitude: "25.2854", longitude: "51.5310", population: 796947 },
  "SA": { name: "Riyadh", latitude: "24.7136", longitude: "46.6753", population: 7676654 },
  "SG": { name: "Singapore", latitude: "1.3521", longitude: "103.8198", population: 5685807 },
  "KR": { name: "Seoul", latitude: "37.5665", longitude: "126.9780", population: 9776000 },
  "LK": { name: "Colombo", latitude: "6.9271", longitude: "79.8612", population: 752993 },
  "SY": { name: "Damascus", latitude: "33.5138", longitude: "36.2765", population: 2503000 },
  "TW": { name: "Taipei", latitude: "25.0330", longitude: "121.5654", population: 2646204 },
  "TJ": { name: "Dushanbe", latitude: "38.5598", longitude: "68.7738", population: 1000000 },
  "TH": { name: "Bangkok", latitude: "13.7563", longitude: "100.5018", population: 10722000 },
  "TL": { name: "Dili", latitude: "-8.5569", longitude: "125.5603", population: 277279 },
  "TR": { name: "Ankara", latitude: "39.9334", longitude: "32.8597", population: 5663322 },
  "TM": { name: "Ashgabat", latitude: "37.9601", longitude: "58.3261", population: 1031992 },
  "AE": { name: "Abu Dhabi", latitude: "24.4539", longitude: "54.3773", population: 1482816 },
  "UZ": { name: "Tashkent", latitude: "41.2995", longitude: "69.2401", population: 2517555 },
  "VN": { name: "Hanoi", latitude: "21.0285", longitude: "105.8542", population: 8053000 },
  "YE": { name: "Sana'a", latitude: "15.3694", longitude: "44.1910", population: 2575347 },
  
  // Europe
  "AL": { name: "Tirana", latitude: "41.3275", longitude: "19.8187", population: 418495 },
  "AD": { name: "Andorra la Vella", latitude: "42.5063", longitude: "1.5218", population: 22886 },
  "AT": { name: "Vienna", latitude: "48.2082", longitude: "16.3738", population: 1911191 },
  "BY": { name: "Minsk", latitude: "53.9045", longitude: "27.5615", population: 1982444 },
  "BE": { name: "Brussels", latitude: "50.8503", longitude: "4.3517", population: 1211000 },
  "BA": { name: "Sarajevo", latitude: "43.8563", longitude: "18.4131", population: 275524 },
  "BG": { name: "Sofia", latitude: "42.6977", longitude: "23.3219", population: 1328120 },
  "HR": { name: "Zagreb", latitude: "45.8150", longitude: "15.9819", population: 688163 },
  "CY": { name: "Nicosia", latitude: "35.1856", longitude: "33.3823", population: 55014 },
  "CZ": { name: "Prague", latitude: "50.0755", longitude: "14.4378", population: 1309000 },
  "DK": { name: "Copenhagen", latitude: "55.6761", longitude: "12.5683", population: 799033 },
  "EE": { name: "Tallinn", latitude: "59.4370", longitude: "24.7536", population: 445688 },
  "FI": { name: "Helsinki", latitude: "60.1699", longitude: "24.9384", population: 658864 },
  "FR": { name: "Paris", latitude: "48.8566", longitude: "2.3522", population: 2175000 },
  "DE": { name: "Berlin", latitude: "52.5200", longitude: "13.4050", population: 3645000 },
  "GR": { name: "Athens", latitude: "37.9838", longitude: "23.7275", population: 664046 },
  "HU": { name: "Budapest", latitude: "47.4979", longitude: "19.0402", population: 1752286 },
  "IS": { name: "Reykjavik", latitude: "64.1466", longitude: "-21.9426", population: 131136 },
  "IE": { name: "Dublin", latitude: "53.3498", longitude: "-6.2603", population: 1173179 },
  "IT": { name: "Rome", latitude: "41.9028", longitude: "12.4964", population: 2860000 },
  "XK": { name: "Pristina", latitude: "42.6629", longitude: "21.1655", population: 204721 },
  "LV": { name: "Riga", latitude: "56.9496", longitude: "24.1052", population: 614618 },
  "LI": { name: "Vaduz", latitude: "47.1410", longitude: "9.5209", population: 5696 },
  "LT": { name: "Vilnius", latitude: "54.6872", longitude: "25.2797", population: 580020 },
  "LU": { name: "Luxembourg", latitude: "49.6116", longitude: "6.1319", population: 124509 },
  "MT": { name: "Valletta", latitude: "35.8989", longitude: "14.5146", population: 6444 },
  "MD": { name: "Chisinau", latitude: "47.0105", longitude: "28.8638", population: 510100 },
  "MC": { name: "Monaco", latitude: "43.7384", longitude: "7.4246", population: 38300 },
  "ME": { name: "Podgorica", latitude: "42.4304", longitude: "19.2594", population: 156169 },
  "NL": { name: "Amsterdam", latitude: "52.3702", longitude: "4.8952", population: 872680 },
  "MK": { name: "Skopje", latitude: "42.0024", longitude: "21.4361", population: 544086 },
  "NO": { name: "Oslo", latitude: "59.9139", longitude: "10.7522", population: 693494 },
  "PL": { name: "Warsaw", latitude: "52.2297", longitude: "21.0122", population: 1790658 },
  "PT": { name: "Lisbon", latitude: "38.7223", longitude: "-9.1393", population: 505526 },
  "RO": { name: "Bucharest", latitude: "44.4268", longitude: "26.1025", population: 1883425 },
  "RU": { name: "Moscow", latitude: "55.7558", longitude: "37.6173", population: 12615279 },
  "SM": { name: "San Marino", latitude: "43.9359", longitude: "12.4472", population: 4040 },
  "RS": { name: "Belgrade", latitude: "44.7866", longitude: "20.4489", population: 1378682 },
  "SK": { name: "Bratislava", latitude: "48.1486", longitude: "17.1077", population: 432864 },
  "SI": { name: "Ljubljana", latitude: "46.0569", longitude: "14.5058", population: 294464 },
  "ES": { name: "Madrid", latitude: "40.4168", longitude: "-3.7038", population: 3223334 },
  "SE": { name: "Stockholm", latitude: "59.3293", longitude: "18.0686", population: 975904 },
  "CH": { name: "Bern", latitude: "46.9480", longitude: "7.4474", population: 133883 },
  "UA": { name: "Kyiv", latitude: "50.4501", longitude: "30.5234", population: 2962180 },
  "GB": { name: "London", latitude: "51.5074", longitude: "-0.1278", population: 8982000 },
  "VA": { name: "Vatican City", latitude: "41.9029", longitude: "12.4534", population: 800 },
  
  // North America
  "AG": { name: "Saint John's", latitude: "17.1274", longitude: "-61.8468", population: 21926 },
  "BS": { name: "Nassau", latitude: "25.0443", longitude: "-77.3504", population: 280000 },
  "BB": { name: "Bridgetown", latitude: "13.0969", longitude: "-59.6145", population: 110000 },
  "BZ": { name: "Belmopan", latitude: "17.2510", longitude: "-88.7590", population: 20000 },
  "CA": { name: "Ottawa", latitude: "45.4215", longitude: "-75.6972", population: 1017449 },
  "CR": { name: "San José", latitude: "9.9281", longitude: "-84.0907", population: 333980 },
  "CU": { name: "Havana", latitude: "23.1136", longitude: "-82.3666", population: 2131480 },
  "DM": { name: "Roseau", latitude: "15.3092", longitude: "-61.3880", population: 14725 },
  "DO": { name: "Santo Domingo", latitude: "18.4861", longitude: "-69.9312", population: 2581827 },
  "SV": { name: "San Salvador", latitude: "13.6929", longitude: "-89.2182", population: 567698 },
  "GD": { name: "St. George's", latitude: "12.0565", longitude: "-61.7486", population: 7500 },
  "GT": { name: "Guatemala City", latitude: "14.6349", longitude: "-90.5069", population: 994938 },
  "HT": { name: "Port-au-Prince", latitude: "18.5944", longitude: "-72.3074", population: 987310 },
  "HN": { name: "Tegucigalpa", latitude: "14.0723", longitude: "-87.1921", population: 1126534 },
  "JM": { name: "Kingston", latitude: "17.9714", longitude: "-76.7931", population: 580000 },
  "MX": { name: "Mexico City", latitude: "19.4326", longitude: "-99.1332", population: 21671908 },
  "NI": { name: "Managua", latitude: "12.1150", longitude: "-86.2362", population: 1028808 },
  "PA": { name: "Panama City", latitude: "8.9824", longitude: "-79.5199", population: 430299 },
  "KN": { name: "Basseterre", latitude: "17.2948", longitude: "-62.7176", population: 12920 },
  "LC": { name: "Castries", latitude: "14.0101", longitude: "-60.9875", population: 22000 },
  "VC": { name: "Kingstown", latitude: "13.1600", longitude: "-61.2248", population: 12909 },
  "TT": { name: "Port of Spain", latitude: "10.6603", longitude: "-61.5089", population: 37074 },
  "US": { name: "Washington, D.C.", latitude: "38.9072", longitude: "-77.0369", population: 705749 },
  
  // South America
  "AR": { name: "Buenos Aires", latitude: "-34.6037", longitude: "-58.3816", population: 3075000 },
  "BO": { name: "La Paz", latitude: "-16.5000", longitude: "-68.1500", population: 877363 },
  "BR": { name: "Brasília", latitude: "-15.8267", longitude: "-47.9218", population: 3055149 },
  "CL": { name: "Santiago", latitude: "-33.4489", longitude: "-70.6693", population: 5614000 },
  "CO": { name: "Bogotá", latitude: "4.7110", longitude: "-74.0721", population: 7413000 },
  "EC": { name: "Quito", latitude: "-0.1807", longitude: "-78.4678", population: 2011388 },
  "GY": { name: "Georgetown", latitude: "6.8013", longitude: "-58.1551", population: 235017 },
  "PY": { name: "Asunción", latitude: "-25.2637", longitude: "-57.5759", population: 524287 },
  "PE": { name: "Lima", latitude: "-12.0464", longitude: "-77.0428", population: 9752000 },
  "SR": { name: "Paramaribo", latitude: "5.8520", longitude: "-55.2038", population: 240924 },
  "UY": { name: "Montevideo", latitude: "-34.9011", longitude: "-56.1645", population: 1319108 },
  "VE": { name: "Caracas", latitude: "10.4806", longitude: "-66.9036", population: 2935000 },
  
  // Oceania
  "AU": { name: "Canberra", latitude: "-35.2809", longitude: "149.1300", population: 431380 },
  "FJ": { name: "Suva", latitude: "-18.1416", longitude: "178.4419", population: 93970 },
  "KI": { name: "South Tarawa", latitude: "1.3382", longitude: "173.0176", population: 63439 },
  "MH": { name: "Majuro", latitude: "7.1315", longitude: "171.1845", population: 27797 },
  "FM": { name: "Palikir", latitude: "6.9248", longitude: "158.1610", population: 6647 },
  "NR": { name: "Yaren", latitude: "-0.5477", longitude: "166.9209", population: 1100 },
  "NZ": { name: "Wellington", latitude: "-41.2865", longitude: "174.7762", population: 215100 },
  "PW": { name: "Ngerulmud", latitude: "7.5007", longitude: "134.6242", population: 391 },
  "PG": { name: "Port Moresby", latitude: "-9.4438", longitude: "147.1803", population: 364125 },
  "WS": { name: "Apia", latitude: "-13.8333", longitude: "-171.7667", population: 36735 },
  "SB": { name: "Honiara", latitude: "-9.4333", longitude: "159.9500", population: 84520 },
  "TO": { name: "Nuku'alofa", latitude: "-21.1393", longitude: "-175.2192", population: 23658 },
  "TV": { name: "Funafuti", latitude: "-8.5167", longitude: "179.2167", population: 6320 },
  "VU": { name: "Port Vila", latitude: "-17.7404", longitude: "168.3210", population: 51437 },
};

export async function seedWorldData() {
  try {
    console.log("Starting world data seed...");
    
    // Clear existing data
    await db.delete(cities);
    await db.delete(regions);
    await db.delete(countries);
    
    console.log("Inserting countries...");
    const insertedCountries: Record<string, number> = {};
    
    for (const country of worldCountries) {
      const [inserted] = await db.insert(countries).values(country).returning();
      insertedCountries[country.code] = inserted.id;
      console.log(`✓ ${country.name} (${country.code})`);
    }
    
    console.log(`\nInserted ${worldCountries.length} countries.`);
    console.log("\nInserting capital cities...");
    
    // Insert capital cities
    let citiesInserted = 0;
    for (const [countryCode, cityData] of Object.entries(capitalCities)) {
      const countryId = insertedCountries[countryCode];
      if (!countryId) {
        console.warn(`Warning: Country ${countryCode} not found for city ${cityData.name}`);
        continue;
      }
      
      await db.insert(cities).values({
        name: cityData.name,
        slug: cityData.name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
        countryId,
        regionId: null,
        isCapital: true,
        latitude: cityData.latitude,
        longitude: cityData.longitude,
        population: cityData.population,
      });
      
      citiesInserted++;
    }
    
    console.log(`\n✓ Inserted ${citiesInserted} capital cities.`);
    console.log("\nWorld data seed completed successfully!");
    console.log(`Total: ${worldCountries.length} countries, ${citiesInserted} cities`);
    
  } catch (error) {
    console.error("Error seeding world data:", error);
    throw error;
  }
}

// Run if executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedWorldData()
    .then(() => {
      console.log("\n✅ World data seeding complete!");
      process.exit(0);
    })
    .catch((error) => {
      console.error("\n❌ World data seeding failed:", error);
      process.exit(1);
    });
}
